FROM openjdk:17-jdk-slim
WORKDIR /usr/src/app
COPY pom.xml .
COPY src ./src
RUN apt-get update && apt-get install -y maven \
    && mvn -B package --file pom.xml
CMD ["java", "-jar", "target/app.jar"]
